on:
  push:
    branches:
      - $default-branch
    tags:
      - "[1-9].[0-9]+.[0-9]+"
jobs:
  build:
    name: App Development
    runs-on: ubuntu-latest
    steps:
      - name: Development Check
        if: startsWith(github.ref, 'refs/heads')
        run: echo "TAG=$GITHUB_SHA" >> $GITHUB_ENV && echo "ENVIRONMENT=development" >> $GITHUB_ENV

      - name: Production Check
        if: startsWith(github.ref, 'refs/tags')
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV && echo "ENVIRONMENT=production" >> $GITHUB_ENV

      - name: Checkout master
        uses: actions/checkout@master

      - name: Test Tag
        run: echo "$TAG-$ENVIRONMENT"
